sudo: required
services:
  - docker

before_install:
  - docker build -t srikanthkasha/docker-react -f Dockerfile.dev .
  - gem install bundler
script:
  - docker run srikanthkasha/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-1-278769346277"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

